Accessibilities branch Pull Request
Peter-Dumbari/Portofolio-Microverse pull request #9
Opened 2023-04-11 15:04 UTC by Peter-Dumbari

# Port folio

in this PR:
- I added `alt` attribute to `img` tag

2023-04-11 15:36 UTC, TuyishimireEric commented
# INVALID ❌ ❌ ❌
### Hi @Peter-Dumbari 👋

While you made a great effort in this project, I can't go ahead and review your code.

## Invalid Code Review Request ❌
Please, this is a **pair-programming project** 😨, Kindly make sure that everyone from your team has contributed equally to the project and submit again once you are done 🙏  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Kindly create  a new PR that follows the Gitflow approach

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

---
_Invalid Code Review Request does not count into the code reviews limit._

2023-04-11 16:36 UTC, BregornOriginal requested changes
## Hi @Team 

## Good job so far!

## There are some issues that you still need to work on to go to the next project but you are almost there!

![one-step-closer-one-more](https://user-images.githubusercontent.com/93630700/231230031-1889895f-7f36-4568-8ab8-f0ac8583766f.gif)

## Highlights

✅ Linters are passing
✅ Good commit history

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 16:36 UTC, BregornOriginal commented on index.html
>                      <li class="nav-link"><a href="#" class="link">About</a></li>
- Kindly as this is your portfolio, it should have a `title` tag like "your name" Portfolio. Or some meaningful for you than just the word Portfolio. In this way you can show a better title on your application 💯

2023-04-11 18:39 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @Team, 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Green linters
✅ ... Good fix accecibility

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 16:51 UTC, Peter-Dumbari commented
# Acessibilities added
in this Merge:
- check the pull request for the full description

2023-04-12 16:52 UTC, merged